apiVersion: apps/v1
kind: Deployment
metadata:
  name: novachat-server
  namespace: novachat
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: aliyafirdous22/novachat-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://novachat-mongodb-service:27017/novachat"
            - name: CLIENT_URL
              value: "http://localhost:3000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: novachat-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"